#!groovy

node {

  currentBuild.result = "SUCCESS"

  try {

    stage ('Checkout') {
      checkout scm
    }

    stage ('Prepare cmd') {

    SNAPSHOT_ID = sh(returnStdout: true, script: """aws ec2 describe-images --image-ids ${env.AMI} --query 'Images[*].BlockDeviceMappings[*].Ebs.SnapshotId' --region ${env.REGION} --output text""").trim()
    //echo "aws ec2 deregister-image --image-id ${env.AMI} && aws ec2 delete-snapshot --snapshot-id ${SNAPSHOT_ID}"

    echo 'Describe the chosen AMI'
    sh "aws ec2 describe-images --image-id ${env.AMI}"
    }

    stage ('Generate artifacts') {
      sh "echo ${env.AMI} > AMI.artifact"
      sh "echo ${SNAPSHOT_ID} > SNAPSHOT.artifact"
      sh "aws ec2 describe-images --image-id ${env.AMI} > AMIDETAIL.artifact"
    }

    // Wait for approval
    input "Destroy AMI: ${env.AMI} ?"

    stage ('Destroy AMI') {
      sh "aws ec2 deregister-image --image-id ${env.AMI} && aws ec2 delete-snapshot --snapshot-id ${SNAPSHOT_ID}"
    }

    stage ("Archive artifacts") {
      archiveArtifacts artifacts: '*.artifact'
    }

    // Clean the workspace
    cleanWs()
  }
  catch (err) {
 
    currentBuild.result = 'FAILURE'
    throw err
  }
}
