#!groovy

node {

  currentBuild.result = "SUCCESS"

  try {

    stage ('Checkout') {
      checkout scm
    }

    stage ('Prepare cmd') {

    SNAPSHOT_ID = sh(returnStdout: true, script: """aws ec2 describe-images --image-ids ${env.AMI} --query 'Images[*].BlockDeviceMappings[*].Ebs.SnapshotId' --region ${env.REGION} --output text""").trim()
    echo "THE FOLLOWING COMMAND WILL BE RUN IF APPROVED:"
    echo "aws ec2 deregister-image --image-id ${env.AMI} && aws ec2 delete-snapshot --snapshot-id ${SNAPSHOT_ID}"
    }

    // Wait for approval
    input "Destroy AMI: ${env.AMI} ?"
 
    // Clean the workspace
    cleanWs()
  }
  catch (err) {
 
    currentBuild.result = 'FAILURE'
    throw err
  }
}
